server:
  port: 8888
  tomcat:
    relaxedPathChars: '<,>,[,\,],^,`,{,|,}'
    relaxedQueryChars: '<,>,[,\,],^,`,{,|,}'
  ssl:
   key-store: classpath:aihf.club.jks
   key-store-password: Aa520184.
   key-store-type: JKS
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/AiBlog?useUnicode=true&&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
   username: root
   password: qwe1230.0
   driver-class-name: com.mysql.cj.jdbc.Driver
   type: com.alibaba.druid.pool.DruidDataSource
  jackson:
   date-format: yyyy-MM-dd HH:mm:ss
   time-zone: GMT+8
  mvc:
    dispatch-options-request: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: qwe1230.0

mybatis:
  type-aliases-package: com.aiblogserver.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.aiblogserver.dao: info
  config: classpath:logback-spring.xml
